dataset_name: bidmc
data_path: datasets/bidmc-ppg-and-respiration-dataset-1.0.0/bidmc_csv

# Model parameters
input_dim: 1000
hidden_dim1: 512
hidden_dim2: 256
hidden_dim3: 64
output_dim: 1
patch_size: 25
d_model: 128
num_heads: 2
ffn_dim: 256
num_layers: 2

batch_size: 80
epochs: 150

lr: 0.001
lr_patience: 8
lr_scheduler: plateau

weight_decay: 0.0001

window_size: 16
window_shift: 2

val_split: 0.2
seed: 42
num_workers: 4

only_save_best_model: true
mode: "only_test"

model_path: "pretrained_models/baseline_bidmc/best_model.pth"